%% options setup

diary on;

options = gaoptimset;
options = gaoptimset(options,'PopulationSize', [ 50 ] );
options = gaoptimset(options,'MigrationDirection', 'both');
options = gaoptimset(options,'MigrationInterval', 3);
options = gaoptimset(options,'MigrationFraction', 0.3);
options = gaoptimset(options,'EliteCount', 7);
options = gaoptimset(options,'CrossoverFraction', 0.5);
options = gaoptimset(options,'Generations', 100);
options = gaoptimset(options,'StallGenLimit', 5);
options = gaoptimset(options,'Display', 'iter');
options = gaoptimset(options,'PlotFcns', {  ...
    @gaplotbestf @gaplotbestindiv @gaplotdistance ...
    @gaplotexpectation @gaplotrange ...
    @gaplotscorediversity @gaplotscores @gaplotselection...
    @gaplotstopping @gaplotmaxconstr });
options = gaoptimset(options,'Vectorized', 'off');
options = gaoptimset(options,'UseParallel', 1 );

gauss = 1;
estimate_tracks = 1;

%% only evolution+gauss cost matrix

cfg_heuristic_evogauss = ga( @optimise_trackplacementheuristic, ...
    28, ... % num constraints
    [],[],[],[], ...
    config_optimdrivebounds_onlyevolution(0, gauss), ...
    config_optimdrivebounds_onlyevolution(1, gauss), ...
    [], ...
    [14,15,16,17,18,19,20,21,26,27,28], ... % int constraints
    options );

savefig('results/optimise_trackplacement_evogauss.fig');

% run the full experiment
evogauss = run_experiments( ...
    config_optimdrive(cfg_heuristic_evogauss, 2, estimate_tracks), ...
    'evolution + gauss heuristic' );
save results/cfg_heuristic_evogauss.mat evogauss;

%% only sym+gauss cost matrix

cfg_heuristic_symgauss = ga( @optimise_trackplacementheuristic, ...
    28, ... % num constraints
    [],[],[],[], ...
    config_optimdrivebounds_onlysym(0, gauss), ...
    config_optimdrivebounds_onlysym(1, gauss), ...
    [], ...
    [14,15,16,17,18,19,20,21,26,27,28], ... % int constraints
    options );

savefig('results/cfg_heuristic_symgauss.fig');

% run the full experiment
symgauss = run_experiments( ...
    config_optimdrive(cfg_heuristic_symgauss, 2, estimate_tracks), ...
    'sym + gauss heuristic' );
save results/cfg_heuristic_symgauss.mat symgauss;


%% mean for finding best optimise_trackplacementheuristic

cfg_heuristicmean = ga( @optimise_trackplacementheuristic, ...
    28, ... % num constraints
    [],[],[],[], ...
    config_optimdrivebounds(0, gauss), ...
    config_optimdrivebounds(1, gauss), ...
    [], ...
    [14,15,16,17,18,19,20,21,26,27,28], ... % int constraints
    options );

savefig('results/optimise_trackplacementheuristic.fig');

% run the full experiment
all = run_experiments( ...
    config_optimdrive(cfg_heuristicmean, 2, estimate_tracks ), ...
    'best all heuristic' );
save results/cfg_heuristicmean.mat all;

%% only contig+gauss cost matrix

cfg_heuristic_contiggauss = ga( @optimise_trackplacementheuristic, ...
    28, ... % num constraints
    [],[],[],[], ...
    config_optimdrivebounds_onlycontig(0, gauss), ...
    config_optimdrivebounds_onlycontig(1, gauss), ...
    [], ...
    [14,15,16,17,18,19,20,21,26,27,28], ... % int constraints
    options );

savefig('results/cfg_heuristic_contiggauss.fig');

% run the full experiment
contiggauss = run_experiments( ...
    config_optimdrive(cfg_heuristic_contiggauss, 2, estimate_tracks), ...
    'contig + gauss heuristic' );

save results/cfg_heuristic_contiggauss.mat contiggauss;

%% only sum+gauss cost matrix

cfg_heuristic_sumgauss = ga( @optimise_trackplacementheuristic, ...
    28, ... % num constraints
    [],[],[],[], ...
    config_optimdrivebounds_onlysum(0, gauss), ...
    config_optimdrivebounds_onlysum(1, gauss), ...
    [], ...
    [14,15,16,17,18,19,20,21,26,27,28], ... % int constraints
    options );

savefig('results/cfg_heuristic_sumgauss.fig');

save results/cfg_heuristic_sumgauss_onlyconfig.mat cfg_heuristic_sumgauss;

% run the full experiment
sum_gauss = run_experiments( ...
    config_optimdrive(cfg_heuristic_sumgauss, 2, estimate_tracks), ...
    'sum + gauss heuristic' );
save results/cfg_heuristic_sumgauss.mat sum_gauss;

