function [ predictions_timespace, matched_tracks, ...
    avg_shift, mean_score, heuristic_score, track_estimate ] = ...
    execute_show( s, config )

% execute a given show, read the file, extract the features,
% generate the cosine (similarity) matrix, generate the cost
% matrices, add them together, (all with a given config) 
% and evaluate performance, and return that
% hint: try running me with execute_show(3, config_getdefault)
% s is show number, there are 6 in the github test set

    [indexes, audio_low, showname] = get_show(s, config.sampleRate);
    
    [C, W, tileWidthSecs, space, T, w] = get_cosinematrix(...
        audio_low, config );
    
    clear audio_low;
        
    C2 = C.^config.cosine_normalization;

    C2 = (C2.*2)-1; 
    
    CN = getcost_sum3( T, C2, W, w, ...
             config.costsum_incentivebalance ...
            ) .* config.use_costsum;  
        
    CS = getcost_symmetry3( T, C2, W, w, ...
         config.costsymmetry_incentivebalance ...
        ) .* config.use_costsymmetry;  
    
    CDG = getcost_contigdiag1( T, C2, W, w, ...
         config.costevolution_incentivebalance ...
        ) .* config.use_costcontigevolution;  

    SCS = getcost_contigstatic( ...
        T, C2, W, w, ...
         config.costcontigpast_incentivebalance, config.contig_windowsize, 0 ... 
        ) .* config.use_costcontigpast;  
    
    SCSF = getcost_contigstatic( ...
        T, C2, W, w, ...
         config.costcontigfuture_incentivebalance, config.contig_windowsize, 1 ...
        ) .* config.use_costcontigfuture; 
    
    SCG = getcost_gaussian( T, W, w, ...
         1, config.costgauss_incentivebalance ) ...
        .* config.use_costgaussian;
    
    SCF = CN+CS+CDG+SCS+SCSF+SCG;
    
    [heuristic_score, mean_score, predictions_timespace, ...
    matched_tracks, avg_shift] = ...
        compute_trackplacement( ...
             SCF, space, indexes, config, showname, ...
             T, C2, tileWidthSecs );
         
    track_estimate = estimate_numbertracks( ...
        SCF, showname, indexes, config );
         
end
