function [ resampled ] = resample_vector( vector, outsize )
% Will take a vector and subsample it

    resampled = vector( ...
        floor( ...
            linspace( 1, length(vector), outsize ) ...
            ) );
end 

