
        figure( 2 );

        pmean = mean(abs(indexes' - predictions_timespace));

        % indexes are in time space
        pheuristicaccuracy = get_heuristicaccuracy( indexes, predictions_timespace );

        fprintf( 'mean=%.2f heuristic=%.2f medshift=%.2f\n\n', ...
            pmean, pheuristicaccuracy, avg_shift  );
       %COMMENTF mean(matched_tracks)

        imagesc(SC);
        title(sprintf('Cost Matrix @ T=%.2fs [SS:%.1f@i%.1f SD:%.1f@i%.1f SY:%.1f@i%.1f CP:%.1f@i%.1f CF:%.1f@i%.1f SU:%.1f@i%.1f GA:%.1f@i%.1f CE:%.1f@i%.1f] CONT%d \n%s\nmean=%.1f heuristic=%.1f meandiff=%.1f shift=%.1f\nWhite=ACTUAL Black=PREDICTED',...
           secondsPerTile,  ...
            use_costsymmetrysum, costsymmetrysum_incentivebalance, ...
            use_costsymmetrydiff, costsymmetrydiff_incentivebalance, ...
            use_costsymmetry, costsymmetry_incentivebalance, ...
            use_costcontigpast, costcontigpast_incentivebalance, ...
            use_costcontigfuture, costcontigfuture_incentivebalance, ...
            use_costsum, costsum_incentivebalance, ...
            use_costgaussian, costgauss_incentivebalance, ...
            use_costcontigevolution, costevolution_incentivebalance, ...
            contig_windowsize, ...
           showname, pmean, pheuristicaccuracy, avg_shift, solution_shift ));
        xlabel('Tiles');
        ylabel('Tiles');
        colorbar;
        draw_scindexes(predictions, indexes_tilespace, w, T);

        figure(3);
        hist(C(1:T^2),50)
        title( sprintf('%s\nCosine Matrix Histogram (Cosine Normalization=%.1f, %d Tiles)', ...
            showname, cosine_normalization, T));
        % figure(3)
        % hist(predictions_timespace-indexes',50);
        % title('shift histogram')