function visualize_costmatrix( results, fig_num )

if( nargin > 1 )
    figure(fig_num);
end

cfg = results.config;
show = results.show;

subplot(2,5,[1,2,6,7]);

imagesc(show.CostMatrix);
title(sprintf(...
'Cost Matrix @ T=%.2fs [SY:%.1f@i%.1f CP:%.1f@i%.1f CF:%.1f@i%.1f SU:%.1f@i%.1f GA:%.1f@i%.1f CE:%.1f@i%.1f] \n%s\nmean=%.1f heuristic=%.1f meandiff=%.1f shift=%.1f\nWhite=ACTUAL Black=PREDICTED',...
    cfg.secondsPerTile,  ...
    cfg.use_costsymmetry, cfg.costsymmetry_incentivebalance, ...
    cfg.use_costcontigpast, cfg.costcontigpast_incentivebalance, ...
    cfg.use_costcontigfuture, cfg.costcontigfuture_incentivebalance, ...
    cfg.use_costsum, cfg.costsum_incentivebalance, ...
    cfg.use_costgaussian, cfg.costgauss_incentivebalance, ...
    cfg.use_costcontigevolution, cfg.costevolution_incentivebalance, ...
   show.showname, results.mean_score, ...
   results.heuristic_score, results.avg_shift, cfg.solution_shift ));
xlabel('Tiles');
ylabel('Tiles');
colorbar;
draw_scindexes(results.predictions, show.indexes./ cfg.secondsPerTile,...
    cfg.minTrackLength, show.T);

subplot(2,5,[5]);
hist(show.CosineMatrix(1:show.T^2),50)
title( sprintf( ...
'%s\nCosine Matrix Histogram (Cosine Normalization=%.1f, %d Tiles)', ...
    show.showname, cfg.cosine_normalization, show.T));

subplot(2,5,[3,4,8,9]);
% in tile space
imagesc(show.CosineMatrix);daspect([1 1 1]);colorbar;colorbar;axis xy;
draw_rectangles( [results.predictions show.T .* cfg.secondsPerTile], 'k' );
draw_indexes(show.indexes ./ cfg.secondsPerTile);
title(sprintf(...
'1-Cosine Matrix\n%s\nCosine Matrix Histogram (Cosine Normalization=%.1f, %d Tiles)',...
    show.showname,cfg.cosine_normalization, show.T));
xlabel('Tiles');
ylabel('Tiles');